services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"  # Use port 5433 on host to avoid conflict with GitHub Actions service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - test-network

  app:
    build:
      context: .
      dockerfile: dockerfile.integration
    container_name: integration-test-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres  # Connect to the local PostgreSQL service
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./test-results:/app/test-results
    networks:
      - test-network
    command: >
      sh -c "
        mkdir -p test-results/integration &&
        pytest --junitxml=test-results/integration/results.xml --tb=short tests/integration/ &&
        echo 'Integration tests completed' &&
        ls -la test-results/integration/ &&
        cat test-results/integration/results.xml
      "

networks:
  test-network:
    driver: bridge
    